on:
  push:
    branches:
      - main # Ganti ke branch default jika berbeda

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy HTML files to server directory
        run: |
          pwd
          sudo cp *.* /var/www/html
